### ISSUE TITLE
Warn about pem files

### ISSUE THREAD

**Issue by minj** [abarreir/crx2ff#6]
Similarly to #5 I think it would be beneficial to warn about (but not skip?) `*.pem` files, i. e. private extension signing keys included in the archive.

For example, chrome warns about it when you load an extension from a directory.

Do you agree?

**Comment by abarreir** [comment]
💯

Why not skipping it though? You just never need such file in an extension archive.

**Comment by minj** [comment]
Sure thing. Just wanted your opinion on the matter
